# Generated by Django 4.2.7 on 2023-12-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotiseria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formulario_rotiseria',
            table='formulario_table',
        ),
    ]
